name: 'Tag Current Git Commit'
description: 'Tags current git commit'
author: 'Gopal Sharma <gps@surya-soft.com>'
inputs:
  GH_TOKEN:
    description: GitHub Token used to interact with GitHub API
    required: True
  TAG_NAME:
    description: Tag name to tag commit with
    required: True
runs:
  using: node12
  main: 'dist/index.js'
